
# https://docs.docker.com/engine/install/ubuntu/

- name: Install Docker
  hosts: localhost

  vars:
    old_docker_packages:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc


  tasks:
    - name: uninstall all conflicting packages
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      loop: "{{ old_docker_packages }}"
    
    - name: Update System
      apt: 
        update_cache: true
        upgrade: dist
    
    - name: Install required system packages
      apt:
        pkg:
          - ca-certificates
          - curl
        state: latest
        update_cache: true 

    - name: Create directory for Docker GPG keys
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Get architecture
      set_fact:
        docker_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
        
    - name: Print architecture variables
      ansible.builtin.debug:
        msg: "Architecture: {{ docker_arch }}, Codename: {{ ansible_lsb.codename }}"
        
    - name: Add Docker repository
      apt_repository:
        repo: >-
          deb [arch={{ docker_arch }}
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        filename: docker
        state: present

    - name: Update repository cache
      apt:
        update_cache: true

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Add users to the Docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true