global:
  sendAnonymousUsage: false

api:
  dashboard: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    network: "traefik"

certificatesResolvers:
  sectigo:
    acme:
      storage: acme.json
      tlsChallenge: {}
      eab:
        kid: {{ TRAEFIK_ACME_EAB_KID }}
        hmacEncoded: {{ TRAEFIK_ACME_EAB_HMACENCODED }}
      caServer: https://acme.sectigo.com/v2/OV
      email: {{ TRAEFIK_ACME_EMAIL }}
  http_resolver:
    acme:
      email: {{ TRAEFIK_ACME_EMAIL }}
      caServer: {{ TRAEFIK_ACME_HTTP_CASERVER }}
      storage: acme.json
      httpChallenge:
        entryPoint: http


log:
  level: DEBUG

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"